name: Deploy Server (Render)
on:
  push:
    branches: [main]
    paths:
      - "server/**"
      - ".github/workflows/deploy-server.yml"

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Render deploy
        run: curl -fsS -X POST "${{ secrets.RENDER_DEPLOY_HOOK }}"
